version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
      - image: circleci/node:8.9.3

    steps:
      - checkout

      - restore_cache:
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: deps-v1-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test --coverage

      - store_artifacts:
          path: coverage
          prefix: coverage
